[cursor]
blink_interval = 660
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3
